name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.16.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test
      
    - name: Create Release
      shell: bash
      if: env.RG_VERSION == ''
      run: |
        echo "RG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "version is: ${{ env.RG_VERSION }}"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RG_VERSION }}
        release_name: ${{ env.RG_VERSION }}
        draft: false
        prerelease: false

